### ISSUE TITLE
Page for User Profile

### ISSUE THREAD

**Issue by ArturRejment** [kamilkow1123/blogpage#1]
Hi! In my opinion, you should create a user profile page.  It could provide us with details about a specific user, his posts and comments, social media links, etc.

Ideally, you can make use of 
> `user/<username>` endpoint

and

> `post` with  an `author` param endpoint

It would definitely bring this application to a whole new level! Gl :)

**Comment by kamilkow1123** [comment]
Great idea!
Working on it

**Comment by kamilkow1123** [comment]
Done!
